openapi: "3.1.0"
info:
  title: "LibraryProject API"
  description: "LibraryProject API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
tags:
  - name: "Biblioteca INFNET - CarrinhoController"
paths:
  /api/v1/carrinho/{id}:
    post:
      summary: "POST api/v1/carrinho/{id}"
      operationId: "criarCarrinho"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "Carrinho criado com sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Carrinho"
        "400":
          description: "Requisição inválida - ID de usuário não encontrado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    get:
      summary: "GET api/v1/carrinho/{id}"
      operationId: "getById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "Carrinho encontrado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Carrinho"
        "204":
          description: "Nenhum conteúdo - Carrinho não encontrado"
        "400":
          description: "Requisição inválida - ID de usuário inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: "DELETE api/v1/carrinho/{id}"
      operationId: "deletarCarrinho"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "Carrinho deletado com sucesso"
        "400":
          description: "Requisição inválida - ID de carrinho não encontrado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/v1/carrinho:
    get:
      summary: "GET api/v1/carrinho"
      operationId: "getAll"
      responses:
        "200":
          description: "Carrinhos recuperados com sucesso"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Carrinho"
        "204":
          description: "Nenhum conteúdo - Nenhum carrinho encontrado"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Emprestimo:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        ativo:
          type: "boolean"
        livro:
          $ref: "#/components/schemas/Livro"
        usuario:
          $ref: "#/components/schemas/Usuario"
        dataVencimento:
          type: "string"
          format: "date-time"
    Livro:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        emprestado:
          type: "boolean"
        titulo:
          type: "string"
        autor:
          type: "string"
        genero:
          type: "string"
        isbn:
          type: "string"
        sinopse:
          type: "string"
        usuario:
          $ref: "#/components/schemas/Usuario"
        emprestimo:
          $ref: "#/components/schemas/Emprestimo"
    Usuario:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        nome:
          type: "string"
        email:
          type: "string"
        senha:
          type: "string"
        meusLivros:
          type: "array"
          items:
            $ref: "#/components/schemas/Livro"
    Carrinho:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        usuario:
          $ref: "#/components/schemas/Usuario"
        livros:
          type: "array"
          items:
            $ref: "#/components/schemas/Livro"
    HttpHeaders:
      type: "object"
      properties: { }
    ResponseEntity:
      type: "object"
      properties:
        headers:
          $ref: "#/components/schemas/HttpHeaders"
      required:
        - "headers"
    Error:
      type: "object"
      properties:
        code:
          type: "integer"
        message: