openapi: "3.1.0"
info:
  title: "LibraryProject API"
  description: "LibraryProject API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
tags:
  - name: "Biblioteca INFNET - EmprestimoController"
paths:
  /api/v1/emprestimo:
    post:
      summary: "POST api/v1/emprestimo"
      operationId: "criarEmprestimo"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmprestimoDto"
        required: true
      responses:
        "200":
          description: "Empréstimo criado com sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmprestimoDto"
        "400":
          description: "Requisição inválida - O corpo do pedido de empréstimo está vazio"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      summary: "GET api/v1/emprestimo"
      operationId: "listarEmprestimos"
      responses:
        responses:
          "200":
            description: "Empréstimos recuperados com sucesso"
            content:
              application/json:
                schema:
                  type: "array"
                  items:
                    $ref: "#/components/schemas/Emprestimo"
          "204":
            description: "Nenhum conteúdo - Nenhum empréstimo encontrado"
          "500":
            description: "Erro interno do servidor"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
  /api/v1/emprestimo/devolver/{id}:
    put:
      summary: "PUT api/v1/emprestimo/devolver/{id}"
      operationId: "devolverEmprestimo"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "Empréstimo devolvido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Emprestimo"
  /api/v1/emprestimo/{id}:
    delete:
      summary: "DELETE api/v1/emprestimo/{id}"
      operationId: "deletarEmprestimo"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "Empréstimo deletado com sucesso"
        "400":
          description: "Requisição inválida - ID de empréstimo não encontrada"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      summary: "GET api/v1/emprestimo/{id}"
      operationId: "listarEmprestimoPorId"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "Empréstimo encontrado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Emprestimo"
        "204":
          description: "Nenhum conteúdo - Empréstimo não encontrado"
        "400":
          description: "Requisição inválida - ID de empréstimo inválida"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/v1/emprestimo/usuario/{usuario}:
    get:
      summary: "GET api/v1/emprestimo/usuario/{usuario}"
      operationId: "listarEmprestimoPorUsuario"
      parameters:
        - name: "usuario"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "Empréstimo encontrado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Emprestimo"
        "204":
          description: "Nenhum conteúdo - Empréstimo não encontrado"
        "400":
          description: "Requisição inválida - Usuário inválido inválida"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/v1/emprestimo/livro/{livro}:
    get:
      summary: "GET api/v1/emprestimo/livro/{livro}"
      operationId: "getEmprestimoByLivro"
      parameters:
        - name: "livro"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "Empréstimo encontrado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Emprestimo"
        "204":
          description: "Nenhum conteúdo - Empréstimo não encontrado"
        "400":
          description: "Requisição inválida - Livro inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Usuario:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        nome:
          type: "string"
        email:
          type: "string"
        senha:
          type: "string"
        meusLivros:
          type: "array"
          items:
            $ref: "#/components/schemas/Livro"
    Emprestimo:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        ativo:
          type: "boolean"
        livro:
          $ref: "#/components/schemas/Livro"
        usuario:
          $ref: "#/components/schemas/Usuario"
        dataVencimento:
          type: "string"
          format: "date-time"
    Livro:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        titulo:
          type: "string"
        autor:
          type: "string"
        genero:
          type: "string"
        isbn:
          type: "string"
        sinopse:
          type: "string"
        usuario:
          $ref: "#/components/schemas/Usuario"
        emprestimo:
          $ref: "#/components/schemas/Emprestimo"
    EmprestimoDto:
      type: "object"
      properties:
        livro:
          $ref: "#/components/schemas/Livro"
        usuario:
          $ref: "#/components/schemas/Usuario"
    HttpHeaders:
      type: "object"
      properties: { }
    ResponseEntity:
      type: "object"
      properties:
        headers:
          $ref: "#/components/schemas/HttpHeaders"
      required:
        - "headers"
    Error:
      type: "object"
      properties:
        code:
          type: "integer"
        message: