openapi: "3.0.3"
info:
  title: "LibraryProject API"
  description: "LibraryProject API"
  version: "1.0.0"
servers:
  - url: "https://LibraryProject"
tags:
  - name: "Biblioteca INFNET - LivroController"
paths:
  /:
    post:
      summary: "POST "
      operationId: "criarLivro"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Livro"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Object"
    get:
      summary: "GET "
      operationId: "listarLivros"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Object"
  /{autor}:
    get:
      summary: "GET {autor}"
      operationId: "listarPorAutor"
      parameters:
        - name: "autor"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Object"
  /{genero}:
    get:
      summary: "GET {genero}"
      operationId: "listarPorGenero"
      parameters:
        - name: "genero"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Object"
  /{titulo}:
    get:
      summary: "GET {titulo}"
      operationId: "listarPorTitulo"
      parameters:
        - name: "titulo"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Object"
  /{id}:
    get:
      summary: "GET {id}"
      operationId: "listarPorId"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Object"
    put:
      summary: "PUT {id}"
      operationId: "atualizarLivro"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Livro"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Object"
  /delete/{id}:
    delete:
      summary: "DELETE delete/{id}"
      operationId: "deletarLivroById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
components:
  schemas:
    Usuario:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        nome:
          type: "string"
        email:
          type: "string"
        senha:
          type: "string"
        meusLivros:
          type: "array"
          items:
            $ref: "#/components/schemas/Livro"
    Emprestimo:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        ativo:
          type: "boolean"
        livro:
          $ref: "#/components/schemas/Livro"
        usuario:
          $ref: "#/components/schemas/Usuario"
        dataVencimento:
          type: "string"
          format: "date-time"
    Livro:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        emprestado:
          type: "boolean"
        titulo:
          type: "string"
        autor:
          type: "string"
        genero:
          type: "string"
        isbn:
          type: "string"
        sinopse:
          type: "string"
        usuario:
          $ref: "#/components/schemas/Usuario"
        emprestimo:
          $ref: "#/components/schemas/Emprestimo"
    Object:
      type: "object"
      properties: { }